# The address-pools lists the IP addresses that MetalLB is
# allowed to allocate. You can have as many
# address pools as you want.
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: main-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.178.101-192.168.178.101
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: external
  namespace: metallb-system
spec:
  # interfaces:
  # - eth0
  ipAddressPools:
  - main-pool
# ---
# apiVersion: metallb.io/v1beta1
# kind: BGPAdvertisement
# metadata:
#   name: external
#   namespace: metallb-system
# spec:
#   ipAddressPools:
#   - main-pool
#   #aggregationLength: 24