apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sysctl-tuning
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: sysctl-tuning
  template:
    metadata:
      labels:
        app: sysctl-tuning
    spec:
      hostNetwork: true
      hostPID: true
      initContainers:
      - name: sysctl-init
        image: busybox:latest
        command: ["/bin/sh", "-c"]
        args:
        - |
          echo "Setting net.core.rmem_max..."
          sysctl -w net.core.rmem_default=2500000
          sysctl -w net.core.wmem_default=2500000
          sysctl -w net.core.rmem_max=2500000
          sysctl -w net.core.wmem_max=2500000
        securityContext:
          privileged: true
      containers:
      - name: sleep-container
        image: busybox:latest
        command: ["/bin/sh", "-c", "sleep infinity"]