apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami-2
spec:
  replicas: 4
  selector:
    matchLabels:
      app: whoami-2
  template:
    metadata:
      labels:
        app: whoami-2
    spec:
      containers:
        - name: whoami
          image: traefik/whoami
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: whoami-2  # Sample service, points to the same deployment
spec:
  selector:
    app: whoami-2
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: networking.cfargotunnel.com/v1alpha1
kind: TunnelBinding
metadata:
  name: whoami-cluster-tunnel
subjects:
  - name: whoami-2  # Points to the second service
    # spec:
    #   fqdn: whoami.qutaiba.de
tunnelRef:
  kind: ClusterTunnel
  name: cluster-tunnel
---
