apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io 
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  sources:
  - repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: 0.20.3 # Latest stable as of now
    helm:
      valueFiles:
      - $values/infra/values/external-secrets.yaml
  - repoURL: https://github.com/roo20/homelab.git
    targetRevision: HEAD
    ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true