# permissions for end users to edit clustertunnels.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clustertunnel-editor-role
rules:
- apiGroups:
  - networking.cfargotunnel.com
  resources:
  - clustertunnels
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.cfargotunnel.com
  resources:
  - clustertunnels/status
  verbs:
  - get
