# permissions for end users to edit tunnelbindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: tunnelbinding-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cloudflare-operator
    app.kubernetes.io/part-of: cloudflare-operator
    app.kubernetes.io/managed-by: kustomize
  name: tunnelbinding-editor-role
rules:
- apiGroups:
  - networking.cfargotunnel.com
  resources:
  - tunnelbindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.cfargotunnel.com
  resources:
  - tunnelbindings/status
  verbs:
  - get
