---
apiVersion: v1
kind: Service
metadata:
  name: couchdb-headless
  namespace: infrastructure
  labels:
    app.kubernetes.io/name: couchdb
    app.kubernetes.io/component: database
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: couchdb
  ports:
    - name: http
      port: 5984
      targetPort: 5984
---
apiVersion: v1
kind: Service
metadata:
  name: couchdb
  namespace: infrastructure
  labels:
    app.kubernetes.io/name: couchdb
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: couchdb
  ports:
    - name: http
      port: 5984
      targetPort: 5984