

crds:
  enabled: true
  
prometheus:
  enabled: true
  servicemonitor:
    enabled: false
    labels: 
      release: prometheus

# Tolerations for control-plane and cloudprovider taints
tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
  - key: "node.cloudprovider.kubernetes.io/uninitialized"
    operator: "Exists"
    effect: "NoSchedule"

# Cainjector tolerations
cainjector:
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "node.cloudprovider.kubernetes.io/uninitialized"
      operator: "Exists"
      effect: "NoSchedule"

# Webhook tolerations
webhook:
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "node.cloudprovider.kubernetes.io/uninitialized"
      operator: "Exists"
      effect: "NoSchedule"