---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-external-secret
  namespace: cloudflare-tunnel
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-cluster-store
    kind: ClusterSecretStore
  target:
    name: cloudflare-external-secret
  data:
    - secretKey: api_token
      remoteRef:
        key: eso
        property: cf_api_token
    - secretKey: tunnel_name
      remoteRef:
        key: eso
        property: cf_tunnel_name
    - secretKey: account_id
      remoteRef:
        key: eso
        property: cf_account_id