apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-secrets
type: Opaque
data:
  CLOUDFLARE_API_TOKEN: <API Key, base64 encoded>
  CLOUDFLARE_API_KEY: <API Key, base64 encoded>
  # CREDENTIAL_FILE is used if found, else CREDENTIAL_SECRET is used to build the file.
  # Either of them is needed when using an existing tunnel
  CLOUDFLARE_TUNNEL_CREDENTIAL_FILE: <~/.cloudflared/tunnelID.json, base64 encoded>
  CLOUDFLARE_TUNNEL_CREDENTIAL_SECRET: <TunnelSecret from ~/.cloudflared/tunnelID.json, base64 encoded>
