storageClass:
  create: true
storageClasses:
  - name: qnap-nfs-csi
    annotations:
      storageclass.kubernetes.io/is-default-class: "true"
    parameters:
      server: 10.0.0.22
      share: /test/k8s
    reclaimPolicy: Delete
    volumeBindingMode: Immediate
    mountOptions:
    - nfsvers=4
    - nolock
  - name: media-nfs
    annotations:
      storageclass.kubernetes.io/is-default-class: "false"
    parameters:
      server: 10.0.0.22
      share: /Media
    reclaimPolicy: Retain
    volumeBindingMode: Immediate
    mountOptions:
    - nfsvers=4
    - nolock

